DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS login;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS marina;
DROP TABLE IF EXISTS carrier;
DROP TABLE IF EXISTS battleship;
DROP TABLE IF EXISTS cruiser;
DROP TABLE IF EXISTS submarine;
DROP TABLE IF EXISTS destroyer;
DROP TABLE IF EXISTS gameroom;

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    email TEXT,
    img TEXT,
    username VARCHAR(30),
    xp INT,
    lever INT
);

CREATE TABLE login (
    user_login_id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    hash TEXT
);

CREATE TABLE friendship (
    friendship_id SERIAL PRIMARY KEY,
    friend1 INT REFERENCES users(user_id),
    friend2 INT REFERENCES users(user_id),
    games_played INT,
    friend1_wins INT,
    friend2_wins INT,
    game_active BOOLEAN
);

INSERT INTO friendship (friend1, friend2, games_played, friend1_wins, friend2_wins, game_active)
VALUES 
    (8, 9, 0, 0, 0, false),
    (8, 10, 0, 0, 0, false),
    (9, 10, 0, 0, 0, false);

CREATE TABLE boards (
    board_id SERIAL PRIMARY KEY,
    is_host BOOLEAN,
    user_id INT REFERENCES users(user_id)
);

CREATE TABLE marina (
    marina_id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    ships_sunk INT
);

CREATE TABLE carrier (
    carrier_id SERIAL PRIMARY KEY,
    marina_id INT REFERENCES marina(marina_id),
    is_sunk BOOLEAN
);

CREATE TABLE battleship (
    battleship_id SERIAL PRIMARY KEY,
    marina_id INT REFERENCES marina(marina_id),
    is_sunk BOOLEAN
);

CREATE TABLE cruiser (
    cruiser_id SERIAL PRIMARY KEY,
    marina_id INT REFERENCES marina(marina_id),
    is_sunk BOOLEAN
);

CREATE TABLE submarine (
    submarine_id SERIAL PRIMARY KEY,
    marina_id INT REFERENCES marina(marina_id),
    is_sunk BOOLEAN
);

CREATE TABLE destroyer (
    destroyer_id SERIAL PRIMARY KEY,
    marina_id INT REFERENCES marina(marina_id),
    is_sunk BOOLEAN
);

CREATE TABLE gameroom (
    gameroom_id SERIAL PRIMARY KEY,
    host_id INT REFERENCES users(user_id),
    guest_id INT REFERENCES users(user_id),
    host_board_id INT REFERENCES boards(board_id),
    guest_board_id INT REFERENCES boards(board_id),
    turn INT REFERENCES users(user_id),
    starting_time TIMESTAMP,
    total_turns INT,
    host_hits INT,
    guest_hits INT,
    host_misses INT,
    guest_misses INT,
    host_ships_sunk INT,
    guest_ships_sunk INT
);

ALTER TABLE boards
ADD COLUMN marina_id INT REFERENCES marina(marina_id),
ADD COLUMN l1 VARCHAR(30),
ADD COLUMN l2 VARCHAR(30),
ADD COLUMN l3 VARCHAR(30),
ADD COLUMN l4 VARCHAR(30),
ADD COLUMN l5 VARCHAR(30),
ADD COLUMN l6 VARCHAR(30),
ADD COLUMN l7 VARCHAR(30),
ADD COLUMN l8 VARCHAR(30),
ADD COLUMN l9 VARCHAR(30),
ADD COLUMN l10 VARCHAR(30),
ADD COLUMN l11 VARCHAR(30),
ADD COLUMN l12 VARCHAR(30),
ADD COLUMN l13 VARCHAR(30),
ADD COLUMN l14 VARCHAR(30),
ADD COLUMN l15 VARCHAR(30),
ADD COLUMN l16 VARCHAR(30),
ADD COLUMN l17 VARCHAR(30),
ADD COLUMN l18 VARCHAR(30),
ADD COLUMN l19 VARCHAR(30),
ADD COLUMN l20 VARCHAR(30),
ADD COLUMN l21 VARCHAR(30),
ADD COLUMN l22 VARCHAR(30),
ADD COLUMN l23 VARCHAR(30),
ADD COLUMN l24 VARCHAR(30),
ADD COLUMN l25 VARCHAR(30),
ADD COLUMN l26 VARCHAR(30),
ADD COLUMN l27 VARCHAR(30),
ADD COLUMN l28 VARCHAR(30),
ADD COLUMN l29 VARCHAR(30),
ADD COLUMN l30 VARCHAR(30),
ADD COLUMN l31 VARCHAR(30),
ADD COLUMN l32 VARCHAR(30),
ADD COLUMN l33 VARCHAR(30),
ADD COLUMN l34 VARCHAR(30),
ADD COLUMN l35 VARCHAR(30),
ADD COLUMN l36 VARCHAR(30),
ADD COLUMN l37 VARCHAR(30),
ADD COLUMN l38 VARCHAR(30),
ADD COLUMN l39 VARCHAR(30),
ADD COLUMN l40 VARCHAR(30),
ADD COLUMN l41 VARCHAR(30),
ADD COLUMN l42 VARCHAR(30),
ADD COLUMN l43 VARCHAR(30),
ADD COLUMN l44 VARCHAR(30),
ADD COLUMN l45 VARCHAR(30),
ADD COLUMN l46 VARCHAR(30),
ADD COLUMN l47 VARCHAR(30),
ADD COLUMN l48 VARCHAR(30),
ADD COLUMN l49 VARCHAR(30),
ADD COLUMN l50 VARCHAR(30),
ADD COLUMN l51 VARCHAR(30),
ADD COLUMN l52 VARCHAR(30),
ADD COLUMN l53 VARCHAR(30),
ADD COLUMN l54 VARCHAR(30),
ADD COLUMN l55 VARCHAR(30),
ADD COLUMN l56 VARCHAR(30),
ADD COLUMN l57 VARCHAR(30),
ADD COLUMN l58 VARCHAR(30),
ADD COLUMN l59 VARCHAR(30),
ADD COLUMN l60 VARCHAR(30),
ADD COLUMN l61 VARCHAR(30),
ADD COLUMN l62 VARCHAR(30),
ADD COLUMN l63 VARCHAR(30),
ADD COLUMN l64 VARCHAR(30),
ADD COLUMN l65 VARCHAR(30),
ADD COLUMN l66 VARCHAR(30),
ADD COLUMN l67 VARCHAR(30),
ADD COLUMN l68 VARCHAR(30),
ADD COLUMN l69 VARCHAR(30),
ADD COLUMN l70 VARCHAR(30),
ADD COLUMN l71 VARCHAR(30),
ADD COLUMN l72 VARCHAR(30),
ADD COLUMN l73 VARCHAR(30),
ADD COLUMN l74 VARCHAR(30),
ADD COLUMN l75 VARCHAR(30),
ADD COLUMN l76 VARCHAR(30),
ADD COLUMN l77 VARCHAR(30),
ADD COLUMN l78 VARCHAR(30),
ADD COLUMN l79 VARCHAR(30),
ADD COLUMN l80 VARCHAR(30),
ADD COLUMN l81 VARCHAR(30),
ADD COLUMN l82 VARCHAR(30),
ADD COLUMN l83 VARCHAR(30),
ADD COLUMN l84 VARCHAR(30),
ADD COLUMN l85 VARCHAR(30),
ADD COLUMN l86 VARCHAR(30),
ADD COLUMN l87 VARCHAR(30),
ADD COLUMN l88 VARCHAR(30),
ADD COLUMN l89 VARCHAR(30),
ADD COLUMN l90 VARCHAR(30),
ADD COLUMN l91 VARCHAR(30),
ADD COLUMN l92 VARCHAR(30),
ADD COLUMN l93 VARCHAR(30),
ADD COLUMN l94 VARCHAR(30),
ADD COLUMN l95 VARCHAR(30),
ADD COLUMN l96 VARCHAR(30),
ADD COLUMN l97 VARCHAR(30),
ADD COLUMN l98 VARCHAR(30),
ADD COLUMN l99 VARCHAR(30),
ADD COLUMN l100 VARCHAR(30);

ALTER TABLE marina
ADD COLUMN carrier_id INT REFERENCES carrier(carrier_id),
ADD COLUMN battleship_id INT REFERENCES battleship(battleship_id),
ADD COLUMN cruiser_id INT REFERENCES cruiser(cruiser_id),
ADD COLUMN submarine_id INT REFERENCES submarine(submarine_id),
ADD COLUMN destroyer_id INT REFERENCES destroyer (destroyer_id);

ALTER TABLE carrier
ADD COLUMN pos1 VARCHAR(10),
ADD COLUMN pos2 VARCHAR(10),
ADD COLUMN pos3 VARCHAR(10),
ADD COLUMN pos4 VARCHAR(10),
ADD COLUMN pos5 VARCHAR(10);

ALTER TABLE battleship
ADD COLUMN pos1 VARCHAR(10),
ADD COLUMN pos2 VARCHAR(10),
ADD COLUMN pos3 VARCHAR(10),
ADD COLUMN pos4 VARCHAR(10);

ALTER TABLE cruiser
ADD COLUMN pos1 VARCHAR(10),
ADD COLUMN pos2 VARCHAR(10),
ADD COLUMN pos3 VARCHAR(10);

ALTER TABLE submarine
ADD COLUMN pos1 VARCHAR(10),
ADD COLUMN pos2 VARCHAR(10),
ADD COLUMN pos3 VARCHAR(10);

ALTER TABLE destroyer
ADD COLUMN pos1 VARCHAR(10),
ADD COLUMN pos2 VARCHAR(10);


